version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: STCpostgresespring
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=stc
      - SPRING_DATASOURCE_PASSWORD=stc123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: STCpostgrese
    environment:
      - POSTGRES_USER=stc
      - POSTGRES_PASSWORD=stc123

        springbootapp:
          image: springbootapp:latest
          network_mode: bridge
          container_name: STCspringboot
          expose:
            - 8080
          ports:
            - 8080:8080
          restart: unless-stopped
          depends_on:
            - STCpostgrese
          links:
            - STCpostgrese

